@extends('layouts.app')
@section('content')

@if (($user->has_reset_password == 0))
<div class="alert alert-danger alert-dismissible fade show pt-1 pb-0 mb-0" id="alert" role="alert">
  <h5 class="mb-0 mt-0"><strong>Warning!</strong></h5>
  <p>The password of your account is still the default password generated by your manager. It is recommended to change your default password. To reset your default password click <a href="/user_area/change_password/" class="alert-link">here</a>
  . </p>
</div>
@endif
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      @if (session('status'))
      <div class="alert alert-success" role="alert">{{ session('status') }}</div>
      @endif
      <div class="row">
        <div class="col-sm-12 pt-0 pb-0 mt-0 mb-0">
          <h4 class="text-center mt-0 pt-0">Previous Holiday Requests <img src="https://upload.wikimedia.org/wikipedia/en/3/35/Information_icon.svg" data-toggle="tooltip" title="Recently requested holiday will show on top of the list" width="3.5%"></h4>
          <ul class="list-group">

            <h6 class="text-center mt-0 pt-0">Holiday entitlement left in current year : {{$number_of_days_left}}</h6>
            <!-- Populate table with sessions user has already signed up to -->
            @foreach ($holidays_requested as $request)
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <a href="/user_area/view_request/{{$request->request_id}}">{{$request->date_from}} <strong>to</strong> {{$request->date_to}}</a>
              <!-- display badge according to status -->
              @if($request->approval == '1')
              <h5><span class="badge badge-pill badge-success">Approved</span></h5>
              @else
              <h5><span class="badge badge-pill badge-danger">Rejected</span></h5>

              @endif
            </li>
            @endforeach

            <a class="btn btn-primary" href="/user_area/request_new_holiday/" role="button">Request New Holiday</a>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
@endsection
